[profile.default]
root = '../..'
src = 'packages/solidity-semantic-money/src'
test = 'packages/solidity-semantic-money/test'
out = 'packages/solidity-semantic-money/out'
solc_version = '0.8.19'
remappings = [
    '@superfluid-finance/solidity-semantic-money/src/=packages/solidity-semantic-money/src/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/']
