[profile.default]
root = '../..'
src = 'packages/ethereum-contracts'
remappings = [
    '@superfluid-finance/ethereum-contracts/contracts/=packages/ethereum-contracts/contracts/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/']
out = 'packages/ethereum-contracts/build/foundry/out'

[profile.ci.fuzz]
runs = 1000