[profile.default]
root = '../..'
libs = ['lib']
src = 'packages/ethereum-contracts'
remappings = [
    '@superfluid-finance/ethereum-contracts/contracts/=packages/ethereum-contracts/contracts/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'hardhat/=node_modules/hardhat/']
out = 'packages/ethereum-contracts/build/foundry/out'
