name: Reusable Workflow | Upload Coverage Reports

on:
  workflow_call:
    secrets:
      codecov_token:
        required: true

jobs:
  upload-coverage-reports:
    name: Upload coverage reports

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download ethereum-contracts-coverage
        uses: actions/download-artifact@v4
        with:
          name: ethereum-contracts-coverage
          path: packages/ethereum-contracts/coverage
      - name: Upload ethereum-contracts-coverage to codecov
        uses: codecov/codecov-action@v4.3.0
        with:
          token: ${{ secrets.codecov_token }}
          files: packages/ethereum-contracts/coverage/lcov.info
          name: ethereum-contracts-coverage
          flags: ethereum-contracts
          fail_ci_if_error: true

      - name: Download sdk-core-coverage
        uses: actions/download-artifact@v4
        with:
          name: sdk-core-coverage
          path: packages/sdk-core/coverage
      - name: Upload sdk-core-coverage to codecov
        uses: codecov/codecov-action@v4.2.0
        with:
          token: ${{ secrets.codecov_token }}
          files: packages/sdk-core/coverage/lcov.info
          name: sdk-core-coverage
          flags: sdk-core
          fail_ci_if_error: true
