name: CD | Create Hardhat-Deployer Stable Release Draft
env:
  GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

on:
  workflow_dispatch:

  push:
    branches:
      - "release-hardhat-deployer-stable"
    paths:
      - "packages/hardhat-deployer/**"
      - ".github/workflows/cd.hardhat-deployer-stable.create-release-drafts.yml"

jobs:
  create-release-draft:
    name: Create Release Draft

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Check package versions
        id: check_versions
        run: |
          # hardhat-deployer
          PUBLISHED_HARDHAT_DEPLOYER_VERSION=`npm show @superfluid-finance/hardhat-deployer@latest version`
          NEW_HARDHAT_DEPLOYER_VERSION=`jq -r .version packages/hardhat-deployer/package.json`
          if [ "$PUBLISHED_HARDHAT_DEPLOYER_VERSION" != "$NEW_HARDHAT_DEPLOYER_VERSION" ];then
            echo "PUBLISHED_HARDHAT_DEPLOYER_VERSION=1" >> $GITHUB_ENV
            echo "sdk-core changed: $PUBLISHED_HARDHAT_DEPLOYER_VERSION -> $NEW_HARDHAT_DEPLOYER_VERSION"
          else
            echo "sdk-core unchanged: $PUBLISHED_HARDHAT_DEPLOYER_VERSION"
          fi

          echo "::set-output name=NEW_HARDHAT_DEPLOYER_VERSION::$NEW_HARDHAT_DEPLOYER_VERSION"

      - name: Create hardhat-deployer stable release draft
        if: env.PUBLISHED_HARDHAT_DEPLOYER_VERSION == 1
        id: create_release_hardhat_deployer
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: hardht-deployer@v${{ steps.check_versions.outputs.NEW_HARDHAT_DEPLOYER_VERSION }}
          release_name: hardhat-deployer@v${{ steps.check_versions.outputs.NEW_HARDHAT_DEPLOYER_VERSION }}
          body: |
            Changes in this hardhat-deployer stable release
            ## Changed
            ## Added
            ## Fixes
            ## Breaking
          draft: true
