name: CD | Create SDK-Redux Stable Release Draft
env:
  GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

on:
  workflow_dispatch:
  push:
    branches:
      - "dev"
    paths:
      - "packages/sdk-redux/**"
      - ".github/workflows/cd.sdk-redux-stable.create-release-drafts.yml"

jobs:

  create-release-draft:
    name: Create Release Draft

    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Check package versions
        id: check_versions
        run: |
          # sdk-redux
          PUBLISHED_SDK_REDUX_VERSION=$(npm show @superfluid-finance/sdk-redux@latest version)
          NEW_SDK_REDUX_VERSION=$(jq -r .version packages/sdk-redux/package.json)
          if [ "$PUBLISHED_SDK_REDUX_VERSION" != "$NEW_SDK_REDUX_VERSION" ];then
            echo "PUBLISHED_SDK_REDUX_VERSION=1" >> "$GITHUB_ENV"
            echo "sdk-redux changed: $PUBLISHED_SDK_REDUX_VERSION -> $NEW_SDK_REDUX_VERSION"
          else
            echo sdk-redux unchanged: "$PUBLISHED_SDK_REDUX_VERSION"
          fi

          echo "NEW_SDK_REDUX_VERSION=$NEW_SDK_REDUX_VERSION" >> "$GITHUB_OUTPUT"

      - name: Create sdk-redux stable release draft
        if: env.PUBLISHED_SDK_REDUX_VERSION == 1
        id: create_release_sdk_redux
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: sdk-redux@v${{ steps.check_versions.outputs.NEW_SDK_REDUX_VERSION }}
          release_name: sdk-redux@v${{ steps.check_versions.outputs.NEW_SDK_REDUX_VERSION }}
          body: |
            Changes in this sdk-redux stable release
            ## Changed
            ## Added
            ## Fixes
            ## Breaking
          draft: true
