name: Dev CI/CD

on:
  push:
    branches: ['*']

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.SUPERFLUID_GITHUB_TOKEN }}

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:

    - uses: actions/checkout@v2

    - name: Show contexts
      run: |
        echo github.event_name: ${{ github.event_name }}
        echo github.sha: ${{ github.sha }}
        echo github.repository: ${{ github.repository }}
        echo github.ref: ${{ github.ref }}
        echo github.head_ref: ${{ github.head_ref }}
        echo github.base_ref: ${{ github.base_ref }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build, and test
      run: |
        npm ci
        npm run build
        npm run test

    - name: Upload eth gas report
      uses: actions/upload-artifact@v2
      with:
        name: contracts-eth-gas-report
        path: build/contracts-eth-gas-report.txt

  coverage:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.SUPERFLUID_GITHUB_TOKEN }}

    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install, build, and test
      run: |
        npm ci
        npm run test-coverage

    - name: Create coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage

  master-deploy-goerli:

    needs: [build, coverage]

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.SUPERFLUID_GITHUB_TOKEN }}

    # only publish npm package for master branch push
    if: github.ref == 'refs/heads/master'

    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    #- name: Determine release version
    #  run: |
    #    RELEASE_VERSION=`basename "$GITHUB_REF"`
    #    echo "::set-env name=RELEASE_VERSION::$RELEASE_VERSION"
    #    echo "Release version is $RELEASE_VERSION"

    - name: Build package
      run: |
        npm ci
        npm run build

    - name: Deploy to goerli
      run: |
        npx truffle exec --network goerli scripts/deploy-test-environment.js
      env:
        RELEASE_VERSION: master
        GOERLI_MNEMONIC: ${{ secrets.GOERLI_MNEMONIC }}
        GOERLI_PROVIDER_URL: ${{ secrets.GOERLI_PROVIDER_URL }}
        GOERLI_GAS_PRICE: 100e9 # 100 GWEI!

  master-npm-publish:

    needs: [build, coverage, master-deploy-goerli]

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.SUPERFLUID_GITHUB_TOKEN }}

    # only publish npm package for master branch push
    if: github.ref == 'refs/heads/master'

    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Build package
      run: |
        npm ci
        npm run build

    - name: Publish package
      run: |
        npm ci
        npm run build
        .github/workflows/npm-publish.sh
