name: Deploy Superfluid Protocol to Testnets

on: 
    workflow_dispatch:
        inputs:
            release_version:
            description: 'Protocol Release Version (test/master/v1/etc.)'
            required: true
            default: 'test'

jobs:

    deploy-to-testnets:
        name: Deploy to testnets

        runs-on: ubuntu-latest

        env:
            GITHUB_TOKEN: ${{ secrets.SUPERFLUID_GITHUB_TOKEN }}

        strategy:
            fail-fast: false
            matrix:
                network: [goerli, rinkeby, ropsten, mumbai]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Build
              run: |
                  yarn install --frozen-lockfile
                  cd packages/ethereum-contracts
                  yarn build

            - name: Deploy to prod-testnets
              run: |
                  cd packages/ethereum-contracts
                  npx truffle exec --network ${{ matrix.network }} scripts/deploy-test-environment.js
              env:
                  RELEASE_VERSION: v1
                  GOERLI_MNEMONIC: ${{ secrets.BUILD_AGENT_MNEMONIC  }}
                  GOERLI_PROVIDER_URL: ${{ secrets.GOERLI_PROVIDER_URL }}
                  RINKEBY_MNEMONIC: ${{ secrets.BUILD_AGENT_MNEMONIC  }}
                  RINKEBY_PROVIDER_URL: ${{ secrets.RINKEBY_PROVIDER_URL }}
                  ROPSTEN_MNEMONIC: ${{ secrets.BUILD_AGENT_MNEMONIC  }}
                  ROPSTEN_PROVIDER_URL: ${{ secrets.ROPSTEN_PROVIDER_URL }}
                  MUMBAI_MNEMONIC: ${{ secrets.BUILD_AGENT_MNEMONIC  }}
                  MUMBAI_PROVIDER_URL: ${{ secrets.MUMBAI_PROVIDER_URL }}

