name: Publish Release Package
env:
  GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

on:
  release:
    types: [published]


jobs:
  publish-release:
    name: Publish release package

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Parse Tag
        run: |
          if echo -n "${{ github.ref }}" | grep -qE "refs/tags/ethereum-contracts@";then
            echo "PUBLISH_ETHEREUM_CONTRACTS=1" >> $GITHUB_ENV
          fi
          if echo -n "${{ github.ref }}" | grep -qE "refs/tags/js-sdk@";then
            if echo -n "${{ github.ref }}" | grep -qE "refs/tags/js-sdk@v0.6";then
              echo "PUBLISH_JS_SDK_V0_6=1" >> $GITHUB_ENV
            else
              echo "PUBLISH_JS_SDK=1" >> $GITHUB_ENV
            fi
          fi
          if echo -n "${{ github.ref }}" | grep -qE "refs/tags/sdk-core@";then
            echo "PUBLISH_SDK_CORE=1" >> $GITHUB_ENV
          fi
          if echo -n "${{ github.ref }}" | grep -qE "refs/tags/sdk-redux@";then
            echo "PUBLISH_SDK_REDUX=1" >> $GITHUB_ENV
          fi

      - name: Build package
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Publish ethereum-contracts package
        if: env.PUBLISH_ETHEREUM_CONTRACTS == 1
        run: tasks/npm-publish.sh packages/ethereum-contracts/ latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPMJS_TOKEN: ${{ secrets.NPMJS_TOKEN }}

      - name: Publish js-sdk package
        if: env.PUBLISH_JS_SDK == 1
        run: tasks/npm-publish.sh packages/js-sdk/ latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPMJS_TOKEN: ${{ secrets.NPMJS_TOKEN }}

      - name: Publish js-sdk package
        if: env.PUBLISH_JS_SDK_V0_6 == 1
        run: tasks/npm-publish.sh packages/js-sdk/ v0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPMJS_TOKEN: ${{ secrets.NPMJS_TOKEN }}

      - name: Publish sdk-core package
        if: env.PUBLISH_SDK_CORE == 1
        run: tasks/npm-publish.sh packages/sdk-core/ latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPMJS_TOKEN: ${{ secrets.NPMJS_TOKEN }}

      - name: Publish sdk-redux package
        if: env.PUBLISH_SDK_REDUX == 1
        run: tasks/npm-publish.sh packages/sdk-redux/ latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPMJS_TOKEN: ${{ secrets.NPMJS_TOKEN }}
