name: XKCD Comic Relief

on:
  pull_request:
    types: [closed]

jobs:
  post-xkcd:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      issues: write
      
    if: github.event.pull_request.merged == true
    steps:
      - name: Search relif
        id: search
        run: |
          xkcd_url=https://xkcd.com/${{ github.event.pull_request.number }}
          xkcd_img_url=$(curl -sL $xkcd_url | \
                grep -oe '"https://imgs.xkcd.com/comics/[^"]\+"' | \
                sed 's/"//g' | \
                head -n1)
          echo "xkcd_url=$xkcd_url" >> "$GITHUB_OUTPUT"
          echo "xkcd_img_url=$xkcd_img_url" >> "$GITHUB_OUTPUT"

      - name: Create relif
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
              ## XKCD Comic Relif
              Link: ${{ steps.search.outputs.xkcd_url }}
              ![${{ steps.search.outputs.xkcd_url }}](${{ steps.search.outputs.xkcd_img_url }})
          reactions: laugh
