name: Deploy to Testnets
env:
  GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Protocol release version (test/master/v1/etc.)'
        required: true
        default: 'test'
      only_network:
        description: 'Only a specific network is to be deployed'
        required: false

jobs:

  deploy-to-testnets:
    name: Deploy to testnets

    runs-on: ubuntu-latest

    env:
      RELEASE_VERSION: ${{ github.event.inputs.release_version }}
      GOERLI_MNEMONIC: ${{ secrets.BUILD_AGENT_MNEMONIC  }}
      GOERLI_PROVIDER_URL: ${{ secrets.GOERLI_PROVIDER_URL }}
      RINKEBY_MNEMONIC: ${{ secrets.BUILD_AGENT_MNEMONIC  }}
      RINKEBY_PROVIDER_URL: ${{ secrets.RINKEBY_PROVIDER_URL }}
      ROPSTEN_MNEMONIC: ${{ secrets.BUILD_AGENT_MNEMONIC  }}
      ROPSTEN_PROVIDER_URL: ${{ secrets.ROPSTEN_PROVIDER_URL }}
      MUMBAI_MNEMONIC: ${{ secrets.BUILD_AGENT_MNEMONIC  }}
      MUMBAI_PROVIDER_URL: ${{ secrets.MUMBAI_PROVIDER_URL }}
      KOVAN_MNEMONIC: ${{ secrets.BUILD_AGENT_MNEMONIC }}
      KOVAN_PROVIDER_URL: ${{ secrets.KOVAN_PROVIDER_URL }}
      OPTIMISM_KOVAN_PROVIDER_URL: ${{ secrets.OPTIMISM_KOVAN_PROVIDER_URL }}
      ARBITRUM_RINKEBY_PROVIDER_URL: ${{ secrets.ARBITRUM_RINKEBY_PROVIDER_URL }}
      AVALANCHE_FUJI_PROVIDER_URL: ${{ secrets.AVALANCHE_FUJI_PROVIDER_URL }}

    strategy:
      fail-fast: false
      matrix:
          network: [eth-goerli, eth-rinkeby, eth-ropsten, eth-kovan, eth-mumbai, optimism-kovan, arbitrum-rinkeby, avalanche-fuji]

    steps:
      - uses: actions/checkout@v2

      - name: Check only_network
        if: ${{ github.event.inputs.only_network != '' && github.event.inputs.only_network != matrix.network }}
        run: echo "DO_SKIP=1" >> $GITHUB_ENV

      - name: Use Node.js 14.x
        if: env.DO_SKIP != 1
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build
        if: env.DO_SKIP != 1
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Build and deploy to ${{ matrix.network }}
        if: env.DO_SKIP != 1
        run: |
          cd packages/ethereum-contracts
          npx truffle exec --network ${{ matrix.network }} scripts/deploy-test-environment.js

      - name: Etherscan verification of ${{ matrix.network }} deployment
        if: env.DO_SKIP != 1
        run: |
          cd packages/ethereum-contracts
          if ./tasks/supports-etherscan.sh ${{ matrix.network }};then
            npx truffle exec --network ${{ matrix.network }} scripts/info-print-contract-addresses.js : addresses.vars
            source addresses.vars
            source tasks/etherscan-verify-framework.sh ${{ matrix.network }}
          fi
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
