name: Changelog Reminder

on:
  pull_request:
    types: [opened]

jobs:
  check:
    name: Check which packages have been modified

    runs-on: ubuntu-latest

    outputs:
      build_ethereum_contracts: ${{ env.BUILD_ETHEREUM_CONTRACTS }}
      build_sdk_core: ${{ env.BUILD_SDK_CORE }}
      build_sdk_redux: ${{ env.BUILD_SDK_REDUX }}
      build_spec_haskell: ${{ env.BUILD_SPEC_HASKELL }}

    steps:
      - uses: actions/checkout@v3

      - name: Check changeset
        run: tasks/check-changeset.sh ${{ github.sha }} dev
  
  create-reminder:
    name: Create Changelog reminder in PR discussion

    permissions:
      pull-requests: write
      issues: write

    runs-on: ubuntu-latest

    needs: [check]
    if: needs.check.outputs.build_ethereum_contracts || needs.check.outputs.build_sdk_core || needs.check.outputs.build_sdk_redux || needs.check.outputs.build_spec_haskell

    steps:
      - name: Create Reminder
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
              ## Changelog Reminder

              Reminder to update the CHANGELOG.md for any of the modified packages in this PR.
              - [ ] CHANGELOG.md modified
              - [ ] Double check before merge
          reactions: white_check_mark