name: Publish master branch

on:
    push:
        branches: ["master"]

jobs:

    npm-publish-master:
        name: NPM publish master branch package

        # TODO make this happen faster

        needs: [build, coverage]

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
                  registry-url: https://registry.npmjs.org/

            - name: Publish package to NpmJS Registry
              run: |
                  rm -f packages/ethereum-contracts/.npmrc
                  .github/workflows/npm-publish.sh packages/ethereum-contracts/
                  rm -f packages/js-sdk/.npmrc
                  .github/workflows/npm-publish.sh packages/js-sdk/
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}

            - name: Build package
              run: |
                  yarn install --frozen-lockfile
                  yarn build

            - name: Publish package to Superfluid Registry
              run: |
                  cp .npmrc.template packages/ethereum-contracts/.npmrc
                  .github/workflows/npm-publish.sh packages/ethereum-contracts/
                  cp .npmrc.template packages/js-sdk/.npmrc
                  .github/workflows/npm-publish.sh packages/js-sdk/
              env:
                  GITHUB_TOKEN: ${{ secrets.SUPERFLUID_GITHUB_TOKEN }}
